import{a as q,S as E,i}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="53064153-2d7216b374d8f49c4006b10a4",$="https://pixabay.com/api/";async function m(o,t=1){try{return(await q.get($,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(s){throw console.error("Pixabay API error:",s),s}}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more"),B=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:r,views:n,comments:S,downloads:v})=>`
    <li class="gallery-item">
      <a href="${c}">
        <img src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${v}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),B.refresh()}function R(){h.innerHTML=""}function b(){f.classList.remove("hidden")}function u(){f.classList.add("hidden")}function L(){g.classList.remove("hidden")}function p(){g.classList.add("hidden")}const w=document.querySelector(".form"),M=w.elements["search-text"],O=document.querySelector(".load-more");let l="",a=1,d=0;w.addEventListener("submit",async o=>{if(o.preventDefault(),l=M.value.trim(),!l){i.warning({title:"Oops!",message:"Please enter a search term.",position:"topRight"});return}a=1,R(),p(),b();try{const t=await m(l,a);if(u(),d=t.totalHits,!t.hits||t.hits.length===0){i.error({title:"No results!",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(t.hits),d>a*15&&L(),i.success({title:"Success!",message:`${d} images found!`,position:"topRight"})}catch{u(),i.error({title:"Error!",message:"Something went wrong. Please try again later.",position:"topRight"})}});O.addEventListener("click",async()=>{a+=1,b(),p();try{const o=await m(l,a);u(),y(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),a*15>=d?(p(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{u(),i.error({title:"Error!",message:"Failed to load more images.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
